### ISSUE TITLE
Historie ostatních kurzů

### ISSUE THREAD

**Issue by h4kuna** [h4kuna/exchange#9]
http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_ostatnich_men/kurzy.txt nereaguje na parameter datum. Asi má být jiný?

**Comment by h4kuna** [comment]
Zatím zakomentováno a vypnuto stahování ostatních kurzů.

**Comment by martinknor** [comment]
pouzivaji tohle ?mesic=1&rok=2016, protoze se aktualizuje 1x mesicne...mam poslat PR?

**Comment by h4kuna** [comment]
Já to momentálně nepotřebuji, pokud to využiješ pošli PR.
